// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
SpeedController* RobotMap::driveTrainSpeedController1 = NULL;
SpeedController* RobotMap::driveTrainSpeedController2 = NULL;
SpeedController* RobotMap::driveTrainSpeedController3 = NULL;
SpeedController* RobotMap::driveTrainSpeedController4 = NULL;
RobotDrive* RobotMap::driveTrainRobotDrive41 = NULL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION

void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();

	driveTrainSpeedController1 = new Victor(0);
	lw->AddActuator("DriveTrain", "Speed Controller 1", (Victor*) driveTrainSpeedController1);
	
	driveTrainSpeedController2 = new Victor(1);
	lw->AddActuator("DriveTrain", "Speed Controller 2", (Victor*) driveTrainSpeedController2);
	
	driveTrainSpeedController3 = new Victor(2);
	lw->AddActuator("DriveTrain", "Speed Controller 3", (Victor*) driveTrainSpeedController3);
	
	driveTrainSpeedController4 = new Victor(3);
	lw->AddActuator("DriveTrain", "Speed Controller 4", (Victor*) driveTrainSpeedController4);
	
	driveTrainRobotDrive41 = new RobotDrive(driveTrainSpeedController1, driveTrainSpeedController2,
              driveTrainSpeedController3, driveTrainSpeedController4);
	
	driveTrainRobotDrive41->SetSafetyEnabled(true);
        driveTrainRobotDrive41->SetExpiration(0.1);
        driveTrainRobotDrive41->SetSensitivity(0.5);
        driveTrainRobotDrive41->SetMaxOutput(1.0);



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
